using System;
using System.Collections.Generic;
using System.Data.SQLite;
using System.Globalization;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Xml;

namespace ExperimentMonitor {
 public sealed class ExportProgress { public string Phase; public long CompletedRows,TotalRows; }
 public sealed class ExportResult { public string OutputDirectory; public string[] Files; public long Rows; }
 public static class ExperimentExport {
  internal static int RowsPerVolume=100000;
  static readonly SemaphoreSlim gate=new SemaphoreSlim(1,1);
  static readonly string[] DetailHeaders={"采样时间（本地）","采样时间 UTC","来源","会话","采集轮","轮次开始时间（本地）","设备","测点","名称","站号","地址","寄存器数","工程值","原始数值","显示文本","原始值 HEX","单位","模式","质量","状态","请求 HEX","响应 HEX","耗时 ms","配置版本"};
  static readonly string[] QualityHeaders={"采样时间（本地）","会话","采集轮","设备","测点","质量","状态说明","原始值 HEX","响应 HEX"};
  static readonly string[] logicalOrder={"0006H","D1","D2","D3","T1","D4","D5","D6","D7","D8","T0","T2","T3","T4","T5","D2000","D2209","D2210","D2213","D2207","D2211","D2202","D2212","D2003","D2206","D2001","D2208","DU1","DU2","DU3","DU6","DU7","DU8","ZU6682","ZI6682","ZW66822","D9"};
  static int PointRank(string p){int i=Array.IndexOf(logicalOrder,p);return i<0?Int32.MaxValue:i;}
  static int DeviceRank(string d){string[] order={"DS666","PLC","DDSU666","DJSF6682"};int i=Array.IndexOf(order,d);return i<0?Int32.MaxValue:i;}
  public static Task<ExportResult> ExportAsync(string root,HistoryFilter filter,string parent,string format,IProgress<ExportProgress> progress,CancellationToken token){return Task.Run(()=>Run(root,filter.Copy(),parent,format,progress,token),token);}
  static void Exec(SQLiteConnection c,SQLiteTransaction t,string sql,params object[] values){using(var q=new SQLiteCommand(sql,c,t)){for(int i=0;i<values.Length;i++)q.Parameters.AddWithValue("@p"+i,values[i]??DBNull.Value);q.ExecuteNonQuery();}}
  static string Txt(SQLiteDataReader r,int i){return r.IsDBNull(i)?"":r.GetString(i);}
  static string QLabel(string q,string status){if(q=="good")return "正常";return String.IsNullOrEmpty(status)?(q??"未知"):status;}
  static string Num(double? d){return d.HasValue?d.Value.ToString("G17",CultureInfo.InvariantCulture):"";}
  static string Local(long ticks){return new DateTime(ticks,DateTimeKind.Utc).ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss.fff zzz",CultureInfo.InvariantCulture);}
  static object[] Detail(SQLiteDataReader r){long utc=r.GetInt64(1);return new object[]{Local(utc),new DateTime(utc,DateTimeKind.Utc).ToString("o",CultureInfo.InvariantCulture),Txt(r,3),Txt(r,4),r.GetInt64(5),r.IsDBNull(2)?"":Local(r.GetInt64(2)),Txt(r,6),Txt(r,7),Txt(r,8),r.GetInt32(9),r.GetInt32(10),r.GetInt32(11),r.IsDBNull(12)?null:(object)r.GetDouble(12),r.IsDBNull(13)?null:(object)r.GetDouble(13),Txt(r,14),Txt(r,15),Txt(r,16),Txt(r,17),Txt(r,18),QLabel(Txt(r,18),Txt(r,19)),Txt(r,20),Txt(r,21),r.GetInt64(22),Txt(r,23)};}
  static object[] Quality(SQLiteDataReader r){long utc=r.GetInt64(1);return new object[]{Local(utc),Txt(r,4),r.GetInt64(5),Txt(r,6),Txt(r,7),Txt(r,18),QLabel(Txt(r,18),Txt(r,19)),Txt(r,15),Txt(r,21)};}
  static string CsvCell(object v){if(v==null)return "";if(v is int||v is long||v is double)return Convert.ToString(v,CultureInfo.InvariantCulture);return Journal.Cell(Convert.ToString(v,CultureInfo.InvariantCulture));}
  static void CsvRow(StreamWriter w,object[] cells){w.WriteLine(String.Join(",",cells.Select(CsvCell).ToArray()));}

  sealed class Sheet:IDisposable {
   const string Ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";readonly FileStream file;readonly XmlWriter x;int row;bool disposed;
   public Sheet(string path,object[] header){file=new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None);x=XmlWriter.Create(file,new XmlWriterSettings{Encoding=new UTF8Encoding(false)});x.WriteStartDocument();x.WriteStartElement("worksheet",Ns);x.WriteStartElement("sheetData",Ns);Row(header);}
   static string Col(int n){string s="";while(n>0){n--;s=(char)('A'+n%26)+s;n/=26;}return s;}
   static string Valid(string s){var b=new StringBuilder();for(int i=0;i<s.Length;i++){char c=s[i];if(char.IsHighSurrogate(c)&&i+1<s.Length&&char.IsLowSurrogate(s[i+1]))b.Append(c).Append(s[++i]);else if(XmlConvert.IsXmlChar(c))b.Append(c);else b.Append("[U+").Append(((int)c).ToString("X4")).Append("]");}return b.ToString();}
   public void Row(object[] cells){row++;x.WriteStartElement("row",Ns);x.WriteAttributeString("r",row.ToString(CultureInfo.InvariantCulture));for(int i=0;i<cells.Length;i++){object v=cells[i];if(v==null)continue;string text=Convert.ToString(v,CultureInfo.InvariantCulture);if(text.Length>32767)throw new InvalidDataException("Excel 单元格文字超过 32767 字符。");x.WriteStartElement("c",Ns);x.WriteAttributeString("r",Col(i+1)+row.ToString(CultureInfo.InvariantCulture));if(v is int||v is long||v is double)x.WriteElementString("v",Ns,text);else{x.WriteAttributeString("t","inlineStr");x.WriteStartElement("is",Ns);x.WriteStartElement("t",Ns);x.WriteString(Valid(text));x.WriteEndElement();x.WriteEndElement();}x.WriteEndElement();}x.WriteEndElement();}
   public void Dispose(){if(disposed)return;disposed=true;try{x.WriteEndElement();x.WriteEndElement();x.WriteEndDocument();}finally{try{x.Dispose();}finally{file.Dispose();}}}
  }
  sealed class BookSheets:IDisposable {public int Index;public string Dir;public Sheet Wide,Detail,Quality,Info;public long DetailCount;public BookSheets(string work,int index,string[] wideHeads,object[] infoHeads){Index=index;Dir=Path.Combine(work,"sheets-"+index.ToString("000"));Directory.CreateDirectory(Dir);Wide=new Sheet(Path.Combine(Dir,"sheet1.xml"),wideHeads.Cast<object>().ToArray());Detail=new Sheet(Path.Combine(Dir,"sheet2.xml"),DetailHeaders.Cast<object>().ToArray());Quality=new Sheet(Path.Combine(Dir,"sheet3.xml"),QualityHeaders.Cast<object>().ToArray());Info=new Sheet(Path.Combine(Dir,"sheet4.xml"),infoHeads);}public void Dispose(){Exception first=null;foreach(Sheet s in new[]{Wide,Detail,Quality,Info})try{s.Dispose();}catch(Exception e){if(first==null)first=e;}if(first!=null)throw first;}}
  static void Book(BookSheets b,string path){b.Wide.Dispose();b.Detail.Dispose();b.Quality.Dispose();b.Info.Dispose();const string ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main";using(var z=new ZipArchive(new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None),ZipArchiveMode.Create)){
   Put(z,"[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/><Default Extension=\"xml\" ContentType=\"application/xml\"/><Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/><Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet2.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet3.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/><Override PartName=\"/xl/worksheets/sheet4.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/></Types>");
   Put(z,"_rels/.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/></Relationships>");
   Put(z,"xl/workbook.xml","<workbook xmlns=\""+ns+"\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\"><sheets><sheet name=\"数据宽表\" sheetId=\"1\" r:id=\"rId1\"/><sheet name=\"测点明细\" sheetId=\"2\" r:id=\"rId2\"/><sheet name=\"质量记录\" sheetId=\"3\" r:id=\"rId3\"/><sheet name=\"导出说明\" sheetId=\"4\" r:id=\"rId4\"/></sheets></workbook>");
   var rel=new StringBuilder("<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">");for(int i=1;i<=4;i++)rel.Append("<Relationship Id=\"rId").Append(i).Append("\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet").Append(i).Append(".xml\"/>");rel.Append("</Relationships>");Put(z,"xl/_rels/workbook.xml.rels",rel.ToString());
   for(int i=1;i<=4;i++)using(var input=File.OpenRead(Path.Combine(b.Dir,"sheet"+i+".xml")))using(var output=z.CreateEntry("xl/worksheets/sheet"+i+".xml",CompressionLevel.Optimal).Open())input.CopyTo(output);
  }}
  static void Put(ZipArchive z,string name,string data){using(var w=new StreamWriter(z.CreateEntry(name,CompressionLevel.Optimal).Open(),new UTF8Encoding(false)))w.Write(data);}

  static ExportResult Run(string root,HistoryFilter f,string parent,string format,IProgress<ExportProgress> progress,CancellationToken token){if(format!="xlsx"&&format!="csv")throw new ArgumentException("导出格式必须是 xlsx 或 csv");if(!gate.Wait(0))throw new InvalidOperationException("已有导出正在运行");string work=null;var books=new List<BookSheets>();try{
   parent=Path.GetFullPath(parent);ExportNaming.VerifyDestination(parent);ExportNaming.CheckDestinationSpace(parent);work=ExportNaming.CreateWorkDirectory();string deliverables=Path.Combine(work,"deliverables");Directory.CreateDirectory(deliverables);string spool=Path.Combine(work,"snapshot.sqlite");var sb=new SQLiteConnectionStringBuilder{DataSource=spool,Version=3};long total=0;var pointMeta=new Dictionary<string,Tuple<string,string>>(StringComparer.Ordinal);
   using(var c=new SQLiteConnection(sb.ConnectionString)){c.Open();using(var q=new SQLiteCommand("CREATE TABLE obs(seq INTEGER PRIMARY KEY,utc INTEGER,round_start INTEGER,source TEXT,session TEXT,round INTEGER,device TEXT,point TEXT,description TEXT,slave INTEGER,address INTEGER,count INTEGER,number REAL,raw_number REAL,value TEXT,payload TEXT,unit TEXT,mode TEXT,quality TEXT,status TEXT,tx TEXT,rx TEXT,elapsed INTEGER,config TEXT);CREATE INDEX ix_obs_round ON obs(session,round,seq);CREATE TABLE round_volume(session TEXT,round INTEGER,volume INTEGER,first_utc INTEGER,start_utc INTEGER,row_count INTEGER,PRIMARY KEY(session,round));CREATE TABLE round_index(seq INTEGER PRIMARY KEY,session TEXT,round INTEGER,first_utc INTEGER,start_utc INTEGER,row_count INTEGER);",c))q.ExecuteNonQuery();
    using(var t=c.BeginTransaction()){using(var insert=new SQLiteCommand("INSERT INTO obs VALUES(@s,@u,@rs,@src,@sess,@r,@dev,@p,@d,@sl,@a,@cnt,@n,@raw,@v,@pay,@unit,@mode,@q,@st,@tx,@rx,@ms,@cfg)",c,t)){
      ExperimentHistory.Stream(root,f,o=>{token.ThrowIfCancellationRequested();insert.Parameters.Clear();insert.Parameters.AddWithValue("@s",++total);insert.Parameters.AddWithValue("@u",o.Utc.Ticks);insert.Parameters.AddWithValue("@rs",o.RoundStartedUtc.HasValue?(object)o.RoundStartedUtc.Value.Ticks:DBNull.Value);insert.Parameters.AddWithValue("@src",o.Source??"");insert.Parameters.AddWithValue("@sess",o.Session??"");insert.Parameters.AddWithValue("@r",o.Round);insert.Parameters.AddWithValue("@dev",o.Device??"");insert.Parameters.AddWithValue("@p",o.Point??"");insert.Parameters.AddWithValue("@d",o.Description??"");insert.Parameters.AddWithValue("@sl",o.Slave);insert.Parameters.AddWithValue("@a",o.Address);insert.Parameters.AddWithValue("@cnt",o.Count);insert.Parameters.AddWithValue("@n",o.Number.HasValue?(object)o.Number.Value:DBNull.Value);insert.Parameters.AddWithValue("@raw",o.RawNumber.HasValue?(object)o.RawNumber.Value:DBNull.Value);insert.Parameters.AddWithValue("@v",o.Value??"");insert.Parameters.AddWithValue("@pay",o.Payload??"");insert.Parameters.AddWithValue("@unit",o.Unit??"");insert.Parameters.AddWithValue("@mode",o.Mode??"");insert.Parameters.AddWithValue("@q",o.Quality??"unknown");insert.Parameters.AddWithValue("@st",o.Status??"");insert.Parameters.AddWithValue("@tx",o.Tx??"");insert.Parameters.AddWithValue("@rx",o.Rx??"");insert.Parameters.AddWithValue("@ms",o.Milliseconds);insert.Parameters.AddWithValue("@cfg",o.ConfigVersion??"");insert.ExecuteNonQuery();if(!pointMeta.ContainsKey(o.Point))pointMeta[o.Point]=Tuple.Create(o.Device??"设备",o.Description??PointCatalog.Get(o.Point).Label);if(total%256==0&&progress!=null)progress.Report(new ExportProgress{Phase="固定导出快照",CompletedRows=total,TotalRows=0});},true,token);
    }t.Commit();}}
   if(total==0)throw new InvalidOperationException("所选时间范围和筛选条件没有可导出的记录。");
   List<string> pointIds=(f.Points!=null&&f.Points.Length>0?f.Points.Distinct(StringComparer.Ordinal).ToList():pointMeta.Keys.ToList());pointIds=pointIds.OrderBy(p=>{Tuple<string,string> m;return DeviceRank(pointMeta.TryGetValue(p,out m)?m.Item1:"设备");}).ThenBy(p=>{Tuple<string,string> m;return pointMeta.TryGetValue(p,out m)?m.Item1:"设备";},StringComparer.Ordinal).ThenBy(PointRank).ThenBy(p=>p,StringComparer.Ordinal).ToList();
   long last=0;int vol=1;using(var c=new SQLiteConnection(sb.ConnectionString)){c.Open();
    // Materialize the sorted round index on disk, then assign volumes in bounded keyset batches.
    using(var q=new SQLiteCommand("INSERT INTO round_index(session,round,first_utc,start_utc,row_count) SELECT session,round,MIN(utc),MIN(round_start),COUNT(*) FROM obs GROUP BY session,round ORDER BY COALESCE(MIN(round_start),MIN(utc)),session,round",c))q.ExecuteNonQuery();
    const int batchSize=256;long after=0;while(true){token.ThrowIfCancellationRequested();var rounds=new List<Tuple<long,string,long,long,long?,int>>(batchSize);using(var q=new SQLiteCommand("SELECT seq,session,round,first_utc,start_utc,row_count FROM round_index WHERE seq>@after ORDER BY seq LIMIT @n",c)){q.Parameters.AddWithValue("@after",after);q.Parameters.AddWithValue("@n",batchSize);using(var r=q.ExecuteReader())while(r.Read())rounds.Add(Tuple.Create(r.GetInt64(0),r.GetString(1),r.GetInt64(2),r.GetInt64(3),r.IsDBNull(4)?(long?)null:r.GetInt64(4),r.GetInt32(5)));}if(rounds.Count==0)break;after=rounds[rounds.Count-1].Item1;using(var t=c.BeginTransaction())using(var ins=new SQLiteCommand("INSERT INTO round_volume VALUES(@s,@r,@v,@u,@st,@n)",c,t)){foreach(var round in rounds){token.ThrowIfCancellationRequested();int rows=round.Item6;if(last>0&&last+rows>RowsPerVolume){vol++;last=0;}ins.Parameters.Clear();ins.Parameters.AddWithValue("@s",round.Item2);ins.Parameters.AddWithValue("@r",round.Item3);ins.Parameters.AddWithValue("@v",vol);ins.Parameters.AddWithValue("@u",round.Item4);ins.Parameters.AddWithValue("@st",round.Item5.HasValue?(object)round.Item5.Value:DBNull.Value);ins.Parameters.AddWithValue("@n",rows);ins.ExecuteNonQuery();last+=rows;}t.Commit();}}}
   int volumeCount=Math.Max(1,vol);var headers=new List<string>{"轮次开始时间（本地）","轮次开始时间 UTC","来源","会话","采集轮"};foreach(string p in pointIds){Tuple<string,string> m;pointMeta.TryGetValue(p,out m);PointInfo info=PointCatalog.Get(p);headers.Add((m==null?"设备":m.Item1)+"·"+(m==null?info.Label:m.Item2)+(String.IsNullOrWhiteSpace(info.Unit)?"":"（"+info.Unit+"）"));}
   var infoRows=new List<object[]>{new object[]{"项目","值"},new object[]{"格式版本","1"},new object[]{"时间筛选（本地）",f.FromUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz")+" 至 "+f.ToUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz")+"（开始包含，结束不包含）"},new object[]{"时间筛选（UTC）",f.FromUtc.ToString("o")+" 至 "+f.ToUtc.ToString("o")},new object[]{"来源",f.Source},new object[]{"设备",String.Join(",",f.Devices??new string[0])},new object[]{"测点",String.Join(",",pointIds)},new object[]{"记录条数",total},new object[]{"宽表规则","每个来源会话和采集轮一行；空值留空；不以旧值填充，不做插值。"},new object[]{"轮次开始时间","优先使用采集轮开始时间；旧记录缺失时采用该轮最早实际采样时间。"},new object[]{"数据质量","质量与通讯状态在质量记录页；详细采样时间在测点明细页。"},new object[]{"记录上界","导出时固定的本地 SQLite 快照；导出期间新数据不进入本次导出。"}};
   string[] csvWide=new string[headers.Count];for(int i=0;i<headers.Count;i++)csvWide[i]=headers[i];
   long written=0;
   var files=new List<string>();string stem="实验数据_"+(f.Source=="serial"?"实机":"模拟")+"_"+f.FromUtc.ToLocalTime().ToString("yyyyMMdd-HHmmss")+"_至_"+f.ToUtc.ToLocalTime().ToString("yyyyMMdd-HHmmss");
   for(int v=1;v<=volumeCount;v++){token.ThrowIfCancellationRequested();if(format=="xlsx"){BookSheets b=new BookSheets(work,v,headers.ToArray(),new object[]{"项目","值"});try{PopulateVolume(spool,v,b,infoRows,pointIds,pointMeta,f,token,ref written,total,progress);string name=stem+"_"+v.ToString("000",CultureInfo.InvariantCulture)+".xlsx";Book(b,Path.Combine(deliverables,name));}finally{try{b.Dispose();}catch{}ExportNaming.TryDelete(b.Dir);}files.Add(stem+"_"+v.ToString("000",CultureInfo.InvariantCulture)+".xlsx");}else{
      string suffix="_"+v.ToString("000",CultureInfo.InvariantCulture);string wideName=stem+suffix+"_宽表.csv",detailName=stem+suffix+"_明细.csv",qualityName=stem+suffix+"_质量.csv";
      WriteCsvFiles(spool,v,Path.Combine(deliverables,wideName),Path.Combine(deliverables,detailName),Path.Combine(deliverables,qualityName),csvWide,pointIds,f,token);files.Add(wideName);files.Add(detailName);files.Add(qualityName);}
   }
   string explain="实验监控数据导出\r\n时间范围（本地，开始包含/结束不包含）="+f.FromUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz")+" — "+f.ToUtc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss zzz")+"\r\n时间范围（UTC）="+f.FromUtc.ToString("o")+" — "+f.ToUtc.ToString("o")+"\r\n来源="+f.Source+"\r\n设备="+String.Join(",",f.Devices??new string[0])+"\r\n测点="+String.Join(",",pointIds)+"\r\n记录数="+total+"\r\n宽表每轮一行；缺失为空；不会填充旧值或插值。质量单独输出。旧记录缺少轮次开始时间时，使用本轮最早实际采样。每个采集轮完整放入同一分卷。\r\n"+String.Join("\r\n",files.ToArray());File.WriteAllText(Path.Combine(deliverables,"导出说明.txt"),explain,new UTF8Encoding(true));
   token.ThrowIfCancellationRequested();string final=ExportNaming.PublishDirectory(deliverables,parent,"实验导出-"+DateTime.Now.ToString("yyMMdd-HHmmss")+"-"+Guid.NewGuid().ToString("N").Substring(0,6),token);ExportNaming.TryDelete(work);work=null;if(progress!=null)progress.Report(new ExportProgress{Phase="导出完成",CompletedRows=total,TotalRows=total});return new ExportResult{OutputDirectory=final,Files=files.ToArray(),Rows=total};
  }finally{if(work!=null)ExportNaming.TryDelete(work);gate.Release();}}
  static void PopulateVolume(string spool,int volume,BookSheets book,List<object[]> infoRows,List<string> points,Dictionary<string,Tuple<string,string>> pointMeta,HistoryFilter f,CancellationToken token,ref long written,long total,IProgress<ExportProgress> progress){var cs=new SQLiteConnectionStringBuilder{DataSource=spool,Version=3}.ConnectionString;using(var c=new SQLiteConnection(cs)){c.Open();string sql="SELECT o.* FROM obs o JOIN round_volume v ON v.session=o.session AND v.round=o.round WHERE v.volume=@v ORDER BY o.seq";using(var q=new SQLiteCommand(sql,c)){q.Parameters.AddWithValue("@v",volume);using(var r=q.ExecuteReader())while(r.Read()){token.ThrowIfCancellationRequested();book.Detail.Row(Detail(r));book.Quality.Row(Quality(r));book.DetailCount++;written++;if(written%256==0&&progress!=null)progress.Report(new ExportProgress{Phase="导出明细与质量",CompletedRows=written,TotalRows=total});}}
    // Stream sorted observations and hold at most one round's values (37 bound points).
    StreamWide(c,volume,points,f,cells=>book.Wide.Row(cells),token);
    foreach(object[] row in infoRows)book.Info.Row(row);foreach(string p in points){Tuple<string,string> meta;pointMeta.TryGetValue(p,out meta);PointInfo info=PointCatalog.Get(p);book.Info.Row(new object[]{"测点契约",p+" | "+(meta==null?"设备":meta.Item1)+" | "+(meta==null?info.Label:meta.Item2)+" | "+(String.IsNullOrEmpty(info.Unit)?"":info.Unit)});}
   }}
  static void StreamWide(SQLiteConnection c,int volume,List<string> points,HistoryFilter f,Action<object[]> write,CancellationToken token){string wide="SELECT o.session,o.round,COALESCE(v.start_utc,v.first_utc),o.point,o.number,o.value,o.quality FROM obs o JOIN round_volume v ON v.session=o.session AND v.round=o.round WHERE v.volume=@v ORDER BY COALESCE(v.start_utc,v.first_utc),o.session,o.round,o.seq";using(var q=new SQLiteCommand(wide,c)){q.Parameters.AddWithValue("@v",volume);using(var r=q.ExecuteReader()){string session=null;long round=0,start=0;Dictionary<string,Tuple<double?,string,string>> found=null;Action flush=()=>{if(found==null)return;var cells=new List<object>{Local(start),new DateTime(start,DateTimeKind.Utc).ToString("o",CultureInfo.InvariantCulture),f.Source,session,round};foreach(string p in points){Tuple<double?,string,string> x;if(found.TryGetValue(p,out x)&&x.Item3=="good")cells.Add(x.Item1.HasValue?(object)x.Item1.Value:x.Item2);else cells.Add(null);}write(cells.ToArray());};while(r.Read()){token.ThrowIfCancellationRequested();string nextSession=r.GetString(0);long nextRound=r.GetInt64(1);if(found==null||nextSession!=session||nextRound!=round){flush();session=nextSession;round=nextRound;start=r.GetInt64(2);found=new Dictionary<string,Tuple<double?,string,string>>(StringComparer.Ordinal);}found[r.GetString(3)]=Tuple.Create(r.IsDBNull(4)?(double?)null:r.GetDouble(4),r.IsDBNull(5)?"":r.GetString(5),r.IsDBNull(6)?"unknown":r.GetString(6));}flush();}}}
  static void WriteCsv(string path,string[] headers,Action<StreamWriter> body){using(var w=new StreamWriter(new FileStream(path,FileMode.CreateNew,FileAccess.Write,FileShare.None),new UTF8Encoding(true))){CsvRow(w,headers.Cast<object>().ToArray());body(w);}}
  static void WriteCsvFiles(string spool,int volume,string widePath,string detailPath,string qualityPath,string[] wideHeaders,List<string> points,HistoryFilter f,CancellationToken token){var cs=new SQLiteConnectionStringBuilder{DataSource=spool,Version=3}.ConnectionString;using(var c=new SQLiteConnection(cs)){c.Open();WriteCsv(detailPath,DetailHeaders,w=>{using(var q=new SQLiteCommand("SELECT o.* FROM obs o JOIN round_volume v ON v.session=o.session AND v.round=o.round WHERE v.volume=@v ORDER BY o.seq",c)){q.Parameters.AddWithValue("@v",volume);using(var r=q.ExecuteReader())while(r.Read()){token.ThrowIfCancellationRequested();CsvRow(w,Detail(r));}}});WriteCsv(qualityPath,QualityHeaders,w=>{using(var q=new SQLiteCommand("SELECT o.* FROM obs o JOIN round_volume v ON v.session=o.session AND v.round=o.round WHERE v.volume=@v ORDER BY o.seq",c)){q.Parameters.AddWithValue("@v",volume);using(var r=q.ExecuteReader())while(r.Read()){token.ThrowIfCancellationRequested();CsvRow(w,Quality(r));}}});WriteCsv(widePath,wideHeaders,w=>StreamWide(c,volume,points,f,cells=>CsvRow(w,cells),token));}}
 }
}
