using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ExperimentMonitor {
    /// <summary>BMS-style local history: follow newest while visible; freeze when the user changes filters.</summary>
    public sealed class HistoryPage : UserControl {
        const int PageSize=200;
        readonly string dataRoot,appRoot; readonly MonitorEngine engine; readonly List<Point> allPoints;
        readonly DateTimePicker from=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="yyyy-MM-dd HH:mm:ss",Width=210};
        readonly DateTimePicker to=new DateTimePicker{Format=DateTimePickerFormat.Custom,CustomFormat="yyyy-MM-dd HH:mm:ss",Width=210};
        readonly ComboBox source=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=118};
        readonly CheckedListBox devices=new CheckedListBox{Dock=DockStyle.Fill,CheckOnClick=true,IntegralHeight=false};
        readonly CheckedListBox channels=new CheckedListBox{Dock=DockStyle.Fill,CheckOnClick=true,IntegralHeight=false};
        readonly TextBox deviceSearch=new TextBox{Dock=DockStyle.Fill}; readonly TextBox pointSearch=new TextBox{Dock=DockStyle.Fill};
        readonly DataGridView grid=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,AllowUserToDeleteRows=false,RowHeadersVisible=false,MultiSelect=false,SelectionMode=DataGridViewSelectionMode.FullRowSelect,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,EnableHeadersVisualStyles=false};
        readonly ExperimentChart chart=new ExperimentChart{Dock=DockStyle.Fill};
        readonly Label summary=new Label{AutoSize=true,ForeColor=Color.FromArgb(75,96,120),TextAlign=ContentAlignment.MiddleLeft};
        readonly Label feedback=new Label{AutoSize=true,ForeColor=Color.FromArgb(75,96,120),Text="选择时间范围并查询记录。"};
        readonly Label exportStatus=new Label{AutoSize=true,Visible=false,ForeColor=Color.FromArgb(45,108,175)};
        readonly StyledActionButton query=new StyledActionButton{Text="查询记录",Width=120,BackColor=UiTheme.Blue,IconGlyph="⌕"},follow=new StyledActionButton{Text="回到最新",Width=104},next=new StyledActionButton{Text="更早 200 条",Width=112,Enabled=false},export=new StyledActionButton{Text="导出数据  ▾",Width=128},cancel=new StyledActionButton{Text="取消导出",Visible=false,Width=96},columnPick=new StyledActionButton{Text="列选择  ▾",Width=100};
        readonly ContextMenuStrip exportMenu=new ContextMenuStrip();
        readonly System.Windows.Forms.Timer timer=new System.Windows.Forms.Timer{Interval=1000};
        readonly ComboBox partitionPreset=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=100};
        readonly NumericUpDown partitionCustom=new NumericUpDown{Minimum=1,Maximum=3650,Width=86};
        readonly StyledActionButton applyNext=new StyledActionButton{Text="下个分期生效",Width=116},applyNow=new StyledActionButton{Text="立即新分期",Width=108};
        readonly Dictionary<string,bool> columnVisible=new Dictionary<string,bool>(StringComparer.Ordinal);
        Label emptyHint;
        // 默认列子集:常用三组(温度/实验电表/市电);用户在「列选择」里的勾选优先。
        bool ColumnVisible(string name){bool v;if(columnVisible.TryGetValue(name,out v))return v;string g=PointCatalog.Get(name).Group;return g=="温度"||g=="实验电表"||g=="市电";}
        readonly Label storageStatus=new Label{AutoSize=true,MaximumSize=new Size(1000,0),ForeColor=Color.FromArgb(75,96,120)};
        readonly DataGridView inventory=new DataGridView{Dock=DockStyle.Fill,ReadOnly=true,AllowUserToAddRows=false,RowHeadersVisible=false,AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.Fill,BackgroundColor=Color.White,BorderStyle=BorderStyle.None,EnableHeadersVisualStyles=false};
        readonly Panel storageBody=new Panel{Dock=DockStyle.Fill,Visible=false,Height=170};
        readonly LinkLabel storageToggle=new LinkLabel{Text="本地存储状态与分库设置  ▸",AutoSize=true,LinkColor=Color.FromArgb(45,108,175)};
        readonly ProgressBar progress=new ProgressBar{Width=120,Height=16,Visible=false};
        TableLayoutPanel outerLayout;
        readonly HashSet<string> selectedDevices=new HashSet<string>(StringComparer.Ordinal),selectedPoints=new HashSet<string>(StringComparer.Ordinal);
        CancellationTokenSource exportCancel; bool following=true,explicitSource,queryBusy,pendingViewQuery,pendingFollowQuery,disposed,entered,inventoryBusy,filterDirty=true,wideView=true,rebuildingLists,settingSource,updatingFollowTime; int offset,generation,appliedGeneration,partitionDays=30,serialPartitionDays=30,simulationPartitionDays=30; long lastCommitted=-1,lastCompletedCaptures=-1; string activeSource="simulation",previewSignature=""; DateTime lastInventory=DateTime.MinValue;

        public HistoryPage(List<Point> points,string root,MonitorEngine engine) {
            if(engine==null)throw new ArgumentNullException("engine");this.engine=engine;if(points==null)throw new ArgumentNullException("points");allPoints=points;appRoot=root;dataRoot=Path.Combine(root,"data","storage");Dock=DockStyle.Fill;AutoScaleMode=AutoScaleMode.Dpi;BackColor=Color.FromArgb(239,244,249);Padding=new Padding(8);
            from.Value=DateTime.Now.AddHours(-2);to.Value=DateTime.Now;
            source.Items.AddRange(new object[]{"serial","simulation"});source.SelectedItem="simulation";source.FormattingEnabled=true;source.Format+=(s,e)=>{string v=e.ListItem as string;e.Value=v=="serial"?"实机":"模拟";};
            BuildLayout();LoadPartitionSetting();WireEvents();StyleGrid(grid);StyleGrid(inventory);UiTheme.Apply(this);VisibleChanged+=OnVisibleChanged;Disposed+=(s,e)=>DisposePage();
        }
        void BuildLayout(){
            var viewport=new Panel{Dock=DockStyle.Fill,AutoScroll=true,BackColor=BackColor};var outer=new TableLayoutPanel{Dock=DockStyle.Top,ColumnCount=1,RowCount=7,BackColor=BackColor,Padding=Padding.Empty,MinimumSize=new Size(0,680)};outerLayout=outer;outer.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));outer.RowStyles.Add(new RowStyle(SizeType.Absolute,42));outer.RowStyles.Add(new RowStyle(SizeType.Absolute,82));outer.RowStyles.Add(new RowStyle(SizeType.Absolute,48));outer.RowStyles.Add(new RowStyle(SizeType.Percent,100));outer.RowStyles.Add(new RowStyle(SizeType.Absolute,36));outer.RowStyles.Add(new RowStyle(SizeType.Absolute,25));outer.RowStyles.Add(new RowStyle(SizeType.Absolute,0));viewport.Controls.Add(outer);Controls.Add(viewport);EventHandler resizeViewport=(s,e)=>{outer.Width=viewport.ClientSize.Width;outer.Height=Math.Max(viewport.ClientSize.Height,680);};viewport.Resize+=resizeViewport;resizeViewport(viewport,EventArgs.Empty);
            var titleRow=new Panel{Dock=DockStyle.Fill,BackColor=Color.White,Padding=new Padding(10,5,8,4)};var title=new Label{Text="本地数据记录",Font=new Font("Microsoft YaHei UI",14,FontStyle.Bold),ForeColor=Color.FromArgb(25,52,82),Dock=DockStyle.Left,Width=220,TextAlign=ContentAlignment.MiddleLeft};titleRow.Controls.Add(title);
            export.Anchor=AnchorStyles.Top|AnchorStyles.Right;cancel.Anchor=AnchorStyles.Top|AnchorStyles.Right;exportStatus.Anchor=AnchorStyles.Top|AnchorStyles.Right;progress.Anchor=AnchorStyles.Top|AnchorStyles.Right;titleRow.Controls.Add(export);titleRow.Controls.Add(cancel);titleRow.Controls.Add(exportStatus);titleRow.Controls.Add(progress);titleRow.Resize+=(s,e)=>PositionExport(titleRow);outer.Controls.Add(titleRow,0,0);
            var filters=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true,BackColor=Color.White,Padding=new Padding(7,5,5,3),Margin=new Padding(0,4,0,3)};
            filters.Controls.Add(MakeLabel("数据源"));filters.Controls.Add(new RoundedInputHost(source){Width=130});filters.Controls.Add(MakeLabel("开始时间"));filters.Controls.Add(from);filters.Controls.Add(MakeLabel("结束时间（不含）"));filters.Controls.Add(to);
            var quick=new ComboBox{DropDownStyle=ComboBoxStyle.DropDownList,Width=128};quick.Items.AddRange(new object[]{"快捷范围…","最近 15 分钟","最近 1 小时","最近 2 小时","今天"});quick.SelectedIndex=0;quick.SelectedIndexChanged+=(s,e)=>{if(quick.SelectedIndex==0)return;DateTime now=DateTime.Now;to.Value=NextLocalSecond(now);from.Value=quick.SelectedIndex==1?now.AddMinutes(-15):quick.SelectedIndex==2?now.AddHours(-1):quick.SelectedIndex==3?now.AddHours(-2):now.Date;MarkDirty();quick.SelectedIndex=0;};filters.Controls.Add(new RoundedInputHost(quick){Width=140});filters.Controls.Add(query);filters.Controls.Add(follow);filters.Controls.Add(columnPick);outer.Controls.Add(filters,0,1);
            var summaryRow=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true,BackColor=Color.White,Padding=new Padding(8,4,4,2)};summaryRow.Controls.Add(summary);outer.Controls.Add(summaryRow,0,2);
            var split=new SplitContainer{Dock=DockStyle.Fill,Size=new Size(800,500),Panel1MinSize=190,Panel2MinSize=380,SplitterDistance=258,BackColor=BackColor};outer.Controls.Add(split,0,3);
            var pickLayout=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=6,BackColor=Color.White,Padding=new Padding(5)};pickLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,24));pickLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,40));pickLayout.RowStyles.Add(new RowStyle(SizeType.Percent,32));pickLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,24));pickLayout.RowStyles.Add(new RowStyle(SizeType.Absolute,40));pickLayout.RowStyles.Add(new RowStyle(SizeType.Percent,68));split.Panel1.Controls.Add(pickLayout);
            pickLayout.Controls.Add(MakeLabel("设备"),0,0);pickLayout.Controls.Add(new RoundedInputHost(deviceSearch){Dock=DockStyle.Fill},0,1);pickLayout.Controls.Add(devices,0,2);pickLayout.Controls.Add(MakeLabel("测点"),0,3);pickLayout.Controls.Add(new RoundedInputHost(pointSearch){Dock=DockStyle.Fill},0,4);pickLayout.Controls.Add(channels,0,5);
            foreach(string d in allPoints.Select(p=>p.binding.device).Distinct()){devices.Items.Add(d,true);selectedDevices.Add(d);}
            foreach(Point p in allPoints){channels.Items.Add(p.name+" · "+PointCatalog.Get(p.name).Label,true);selectedPoints.Add(p.name);}
            // 迷你 Tab 样式对齐主选项卡(蓝色下划线选中态)。
            var tabs=new TabControl{Dock=DockStyle.Fill,DrawMode=TabDrawMode.OwnerDrawFixed,ItemSize=new Size(110,30),SizeMode=TabSizeMode.Fixed,Padding=new System.Drawing.Point(10,3)};
            tabs.DrawItem+=(s,e)=>{bool sel=(e.State&DrawItemState.Selected)!=0;using(var b=new SolidBrush(sel?Color.White:Color.FromArgb(247,250,253)))e.Graphics.FillRectangle(b,e.Bounds);TextRenderer.DrawText(e.Graphics,tabs.TabPages[e.Index].Text,tabs.Font,e.Bounds,sel?UiTheme.Blue:UiTheme.Muted,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter|TextFormatFlags.NoPrefix);if(sel)using(var p=new Pen(UiTheme.Blue,2))e.Graphics.DrawLine(p,e.Bounds.Left+18,e.Bounds.Bottom-2,e.Bounds.Right-18,e.Bounds.Bottom-2);};
            var records=new TabPage("数据记录"){BackColor=Color.White};var trend=new TabPage("历史趋势"){BackColor=Color.White};tabs.TabPages.Add(records);tabs.TabPages.Add(trend);records.Controls.Add(grid);
            emptyHint=new Label{Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleCenter,ForeColor=UiTheme.Muted,BackColor=Color.White,Text="当前筛选范围没有记录。",Visible=false};
            records.Controls.Add(emptyHint);emptyHint.BringToFront();
            var chartScroll=new Panel{Dock=DockStyle.Fill,AutoScroll=true};chart.Dock=DockStyle.Top;chartScroll.Controls.Add(chart);trend.Controls.Add(chartScroll);split.Panel2.Controls.Add(tabs);
            var pager=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false,BackColor=Color.White,Padding=new Padding(4,0,2,0)};pager.Controls.Add(next);pager.Controls.Add(feedback);outer.Controls.Add(pager,0,4);
            storageToggle.Margin=new Padding(8,4,0,2);outer.Controls.Add(storageToggle,0,5);
            BuildStorageBody();
            // Fold-out storage controls are placed beneath the record panel without introducing another tab.
            outer.Controls.Add(storageBody,0,6);
            var view=new CheckBox{Text="按采集轮宽表显示",Checked=true,AutoSize=true,Margin=new Padding(8,7,8,0)};var viewRow=(FlowLayoutPanel)summaryRow;viewRow.Controls.Add(view);columnPick.Enabled=view.Checked;view.CheckedChanged+=async(s,e)=>{wideView=view.Checked;columnPick.Enabled=view.Checked;generation++;if(!filterDirty){if(queryBusy)pendingViewQuery=true;else await ApplyAndQuery();}};
            grid.ScrollBars=ScrollBars.Both;grid.AutoSizeColumnsMode=DataGridViewAutoSizeColumnsMode.None;grid.RowTemplate.Height=28;grid.ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.AutoSize;grid.ColumnHeadersDefaultCellStyle.WrapMode=DataGridViewTriState.True;
        }
        void BuildStorageBody(){
            var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,Padding=new Padding(8),BackColor=Color.White};shell.RowStyles.Add(new RowStyle(SizeType.AutoSize));shell.RowStyles.Add(new RowStyle(SizeType.Absolute,60));shell.RowStyles.Add(new RowStyle(SizeType.Percent,100));
            var settings=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=true,AutoSize=true};settings.Controls.Add(MakeLabel("分库周期"));partitionPreset.Items.AddRange(new object[]{"7 天","15 天","30 天","自定义"});partitionPreset.SelectedIndex=2;settings.Controls.Add(new RoundedInputHost(partitionPreset){Width=112});settings.Controls.Add(new RoundedInputHost(partitionCustom){Width=96});settings.Controls.Add(applyNext);settings.Controls.Add(applyNow);settings.Controls.Add(storageStatus);shell.Controls.Add(settings,0,0);
            var invHeading=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};invHeading.Controls.Add(MakeLabel("本地数据库（按来源分开保存）"));var refresh=new StyledActionButton{Text="刷新清单",Width=96};refresh.Click+=(s,e)=>RefreshInventory(true);invHeading.Controls.Add(refresh);shell.Controls.Add(invHeading,0,1);
            var cols=new[]{"来源","数据库文件","大小 MiB","状态"};foreach(string c in cols)inventory.Columns.Add(c,c);inventory.Columns[0].FillWeight=45;inventory.Columns[1].FillWeight=200;inventory.Columns[2].FillWeight=55;inventory.Columns[3].FillWeight=85;shell.Controls.Add(inventory,0,2);storageBody.Controls.Add(shell);
            storageToggle.LinkClicked+=(s,e)=>{storageBody.Visible=!storageBody.Visible;outerLayout.RowStyles[6].Height=storageBody.Visible?190:0;storageToggle.Text=storageBody.Visible?"本地存储状态与分库设置  ▾":"本地存储状态与分库设置  ▸";};
        }
        void WireEvents(){
            query.Click+=async(s,e)=>{following=false;offset=0;await ApplyAndQuery();};follow.Click+=async(s,e)=>{offset=0;SetToNow();MarkDirty();following=true;await ApplyAndQuery();};next.Click+=async(s,e)=>{if(next.Enabled){offset+=PageSize;await RunQuery(false);}};
            source.SelectedIndexChanged+=(s,e)=>{if(source.SelectedItem==null)return;if(!settingSource){explicitSource=true;following=false;offset=0;MarkDirty();}LoadSourcePartitionSetting();RefreshStorageStatus();RefreshInventory(false);};
            devices.ItemCheck+=(s,e)=>{if(rebuildingLists)return;string item=devices.Items[e.Index] as string;bool check=e.NewValue==CheckState.Checked;BeginInvoke((Action)(()=>{if(check)selectedDevices.Add(item);else selectedDevices.Remove(item);offset=0;following=false;MarkDirty();RebuildVisibleDevices();RebuildVisiblePoints();}));};channels.ItemCheck+=(s,e)=>{if(rebuildingLists)return;string item=channels.Items[e.Index] as string;string point=item.Split(new[]{" · "},StringSplitOptions.None)[0];bool check=e.NewValue==CheckState.Checked;BeginInvoke((Action)(()=>{if(check)selectedPoints.Add(point);else selectedPoints.Remove(point);offset=0;following=false;MarkDirty();RebuildVisiblePoints();}));};
            from.ValueChanged+=(s,e)=>{if(!updatingFollowTime){following=false;MarkDirty();}};to.ValueChanged+=(s,e)=>{if(!updatingFollowTime){following=false;MarkDirty();}};deviceSearch.TextChanged+=(s,e)=>RebuildVisibleDevices();pointSearch.TextChanged+=(s,e)=>RebuildVisiblePoints();
            exportMenu.Items.Add("导出为 Excel 工作簿…",null,async(s,e)=>await ExportAsync("xlsx"));exportMenu.Items.Add("导出为 CSV…",null,async(s,e)=>await ExportAsync("csv"));export.Click+=(s,e)=>exportMenu.Show(export,new System.Drawing.Point(0,export.Height));cancel.Click+=(s,e)=>{if(exportCancel!=null)exportCancel.Cancel();};
            applyNext.Click+=(s,e)=>ApplyPartition(false);applyNow.Click+=(s,e)=>ApplyPartition(true);
            // 列选择弹出面板:勾选状态只影响宽表显示列,不改变查询语义。
            columnPick.Click+=(s,e)=>{
                var list=new CheckedListBox{Width=250,Height=380,CheckOnClick=true,IntegralHeight=false,BorderStyle=BorderStyle.FixedSingle,BackColor=Color.White};
                foreach(Point p in allPoints)list.Items.Add(p.name+" · "+PointCatalog.Get(p.name).Label,ColumnVisible(p.name));
                list.ItemCheck+=(ls,le)=>{string n=list.Items[le.Index].ToString().Split(new[]{" · "},StringSplitOptions.None)[0];columnVisible[n]=le.NewValue==CheckState.Checked;try{list.BeginInvoke((Action)(async()=>{if(!filterDirty){if(queryBusy)pendingViewQuery=true;else await ApplyAndQuery();}}));}catch{}};
                var host=new ToolStripControlHost(list){Margin=Padding.Empty,Padding=new Padding(2)};
                var drop=new ToolStripDropDown();drop.Items.Add(host);drop.Show(columnPick,new System.Drawing.Point(0,columnPick.Height));
            };
            timer.Tick+=(s,e)=>FollowTick();
        }
        static Label MakeLabel(string text){return new Label{Text=text,AutoSize=true,Margin=new Padding(4,7,4,3),ForeColor=Color.FromArgb(88,105,125)};}
        void RebuildVisibleDevices(){if(disposed)return;rebuildingLists=true;try{string q=deviceSearch.Text.Trim();devices.BeginUpdate();devices.Items.Clear();foreach(string d in allPoints.Select(p=>p.binding.device).Distinct().Where(x=>x.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0)){int i=devices.Items.Add(d);devices.SetItemChecked(i,selectedDevices.Contains(d));}devices.EndUpdate();}finally{rebuildingLists=false;}}
        void RebuildVisiblePoints(){if(disposed)return;rebuildingLists=true;try{string q=pointSearch.Text.Trim();channels.BeginUpdate();channels.Items.Clear();foreach(Point p in allPoints){string dev=p.binding.device,name=p.name+" · "+PointCatalog.Get(p.name).Label;if(selectedDevices.Contains(dev)&&name.IndexOf(q,StringComparison.OrdinalIgnoreCase)>=0){int i=channels.Items.Add(name);channels.SetItemChecked(i,selectedPoints.Contains(p.name));}}channels.EndUpdate();}finally{rebuildingLists=false;}}
        static void StyleGrid(DataGridView v){v.ColumnHeadersHeight=56;v.ColumnHeadersHeightSizeMode=DataGridViewColumnHeadersHeightSizeMode.AutoSize;v.ColumnHeadersDefaultCellStyle.WrapMode=DataGridViewTriState.True;v.ColumnHeadersDefaultCellStyle.BackColor=Color.FromArgb(232,241,250);v.ColumnHeadersDefaultCellStyle.ForeColor=Color.FromArgb(29,58,89);v.ColumnHeadersDefaultCellStyle.Font=new Font("Microsoft YaHei UI",9,FontStyle.Bold);v.ColumnHeadersDefaultCellStyle.SelectionBackColor=Color.FromArgb(232,241,250);v.DefaultCellStyle.SelectionBackColor=Color.FromArgb(211,231,250);v.DefaultCellStyle.SelectionForeColor=Color.FromArgb(25,52,82);v.AlternatingRowsDefaultCellStyle.BackColor=Color.FromArgb(248,251,254);}
        void PositionExport(Control parent){progress.Location=new System.Drawing.Point(Math.Max(10,parent.ClientSize.Width-450),10);exportStatus.Location=new System.Drawing.Point(Math.Max(10,parent.ClientSize.Width-315),11);cancel.Location=new System.Drawing.Point(Math.Max(10,parent.ClientSize.Width-214),5);export.Location=new System.Drawing.Point(Math.Max(10,parent.ClientSize.Width-138),4);}
        public void EnterPage(string active){if(!String.IsNullOrEmpty(active))activeSource=active;if(!explicitSource&&following)SetSource(activeSource);if(!entered){entered=true;SetToNow();following=true;MarkDirty();}if(Visible){timer.Start();RefreshInventory(true);RefreshStorageStatus();if(following){SetToNow();StartQuery();}}}
        public void SetActiveSource(string value){if(String.IsNullOrEmpty(value))return;activeSource=value;if(explicitSource||!following)return;SetSource(value);offset=0;SetToNow();following=true;MarkDirty();if(Visible)StartQuery();}
        void OnVisibleChanged(object s,EventArgs e){if(Visible){if(entered){timer.Start();RefreshInventory(true);RefreshStorageStatus();if(following){SetToNow();StartQuery();}}}else timer.Stop();}
        void SetSource(string value){int i=source.Items.IndexOf(value);if(i>=0&&source.SelectedIndex!=i){settingSource=true;try{source.SelectedItem=value;}finally{settingSource=false;}}}
        static DateTime TruncateToDisplayedSecond(DateTime value){return new DateTime(value.Year,value.Month,value.Day,value.Hour,value.Minute,value.Second,DateTimeKind.Local);}
        internal static DateTime LocalDisplaySecondToUtc(DateTime value){return TruncateToDisplayedSecond(value).ToUniversalTime();}
        internal static DateTime NextLocalSecond(DateTime value){DateTime second=TruncateToDisplayedSecond(value);return second.AddSeconds(1);}
        void SetToNow(){DateTime upper=NextLocalSecond(DateTime.Now);if(upper>to.MaxDate)upper=TruncateToDisplayedSecond(to.MaxDate);updatingFollowTime=true;try{to.Value=upper;}finally{updatingFollowTime=false;}}
        void StartQuery(){if(queryBusy){if(following&&Visible)pendingFollowQuery=true;return;}Task<bool> ignored=RunQuery(true);}
        void MarkDirty(){if(disposed)return;generation++;filterDirty=true;feedback.Text="筛选条件已更改；点击“查询记录”后应用。";}
        string Signature(HistoryFilter f){return f.Source+"|"+f.FromUtc.Ticks+"|"+f.ToUtc.Ticks+"|"+String.Join(",",f.Devices.OrderBy(x=>x))+"|"+String.Join(",",f.Points.OrderBy(x=>x));}
        HistoryFilter MakeFilter(){DateTime a=TruncateToDisplayedSecond(from.Value),b=TruncateToDisplayedSecond(to.Value);if(b<=a)throw new InvalidOperationException("结束时间必须晚于开始时间（结束时刻不包含）。");string[] ds=selectedDevices.ToArray();string[] ps=allPoints.Where(p=>selectedDevices.Contains(p.binding.device)&&selectedPoints.Contains(p.name)).Select(p=>p.name).ToArray();if(ds.Length==0||ps.Length==0)throw new InvalidOperationException("请至少选择一台设备和一个测点。");return new HistoryFilter{FromUtc=a.ToUniversalTime(),ToUtc=b.ToUniversalTime(),Source=(string)source.SelectedItem,Devices=ds,Points=ps};}
        async Task<bool> ApplyAndQuery(){return await RunQuery(true);}
        sealed class HistoryLoad{public List<StoredObservation> Rows;public long Total;public int Units;}
        HistoryLoad LoadPreview(HistoryFilter f,int page,bool roundView){if(roundView){long total;List<List<StoredObservation>> rounds=ExperimentHistory.QueryRoundPage(dataRoot,f,page,PageSize,out total,false);return new HistoryLoad{Rows=rounds.SelectMany(x=>x).ToList(),Total=total,Units=rounds.Count};}return new HistoryLoad{Rows=ExperimentHistory.QueryPage(dataRoot,f,page,PageSize),Total=ExperimentHistory.Count(dataRoot,f),Units=0};}
        async Task<bool> RunQuery(bool latest){if(queryBusy||disposed)return false;if(!Visible)return false;queryBusy=true;int token=++generation;query.Enabled=false;feedback.Text="正在查询记录…";try{HistoryFilter f=MakeFilter();string signature=Signature(f);int page=latest?0:offset;bool roundView=wideView;HistoryLoad data=await Task.Run(()=>LoadPreview(f,page,roundView));if(disposed||token!=generation||(string)source.SelectedItem!=f.Source||roundView!=wideView)return false;ShowRows(data.Rows,f);appliedGeneration=token;offset=page;previewSignature=signature;filterDirty=false;next.Enabled=page+data.Units<data.Total&&(wideView?data.Units==PageSize:data.Rows.Count==PageSize);summary.Text=(following?"● 跟随最新":"○ 历史查询")+"　·　"+(f.Source=="serial"?"实机":"模拟")+"　·　筛选共 "+data.Total.ToString("N0")+(wideView?" 轮":" 条")+"　·　第 "+(page/PageSize+1)+" 页，显示 "+(wideView?data.Units.ToString("N0")+" 轮":data.Rows.Count.ToString("N0")+" 条");feedback.Text=data.Total==0?"当前筛选范围没有记录。":(wideView?"当前页显示完整采集轮；":"当前页显示逐测点明细；")+"（本地时间；结束时刻不包含）";return true;}
            catch(Exception ex){if(!disposed&&token==generation){grid.Rows.Clear();chart.Clear();feedback.Text="查询失败："+ex.Message;summary.Text="记录查询不可用";}return false;}
            finally{queryBusy=false;bool rerun=(pendingFollowQuery&&following)||(pendingViewQuery&&!filterDirty);pendingFollowQuery=pendingViewQuery=false;if(!disposed){query.Enabled=true;if(rerun&&Visible)try{BeginInvoke((Action)StartQuery);}catch{StartQuery();}}}}
        void ShowRows(List<StoredObservation> rows,HistoryFilter filter){grid.Rows.Clear();chart.Clear();if(emptyHint!=null)emptyHint.Visible=rows.Count==0;if(wideView)BuildWidePreview(rows,filter);else BuildDetailPreview(rows);foreach(StoredObservation r in rows)chart.Add(new Observation{Point=r.Point,Utc=r.Utc,Number=r.Number,Quality=r.Quality});chart.SelectPoints(filter.Points);chart.Height=chart.RequiredHeight;}
        void BuildDetailPreview(List<StoredObservation> rows){grid.Columns.Clear();string[] headers={"采样时间（本地）","测点","名称","设备","工程值","原始值 HEX","单位","质量"};int[] widths={165,85,150,100,160,150,100,110};for(int i=0;i<headers.Length;i++)grid.Columns.Add(headers[i],headers[i]);for(int i=0;i<widths.Length;i++)grid.Columns[i].Width=widths[i];foreach(StoredObservation r in rows){string engineering=r.Number.HasValue?r.Number.Value.ToString("G17",System.Globalization.CultureInfo.InvariantCulture):r.Value;string raw=r.RawNumber.HasValue?r.RawNumber.Value.ToString("G17",System.Globalization.CultureInfo.InvariantCulture):r.Payload;grid.Rows.Add(r.Utc.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss.fff"),r.Point,r.Description,r.Device,engineering,raw,r.Unit,QualityLabel(r.Quality));}}
        void BuildWidePreview(List<StoredObservation> rows,HistoryFilter filter){grid.Columns.Clear();grid.Columns.Add("time","轮次开始时间（本地）");grid.Columns.Add("round","采集轮");var points=allPoints.Select((p,index)=>new{Point=p,Index=index}).Where(x=>filter.Points.Contains(x.Point.name)&&ColumnVisible(x.Point.name)).OrderBy(x=>DeviceRank(x.Point.binding.device)).ThenBy(x=>x.Index).Select(x=>x.Point).ToList();
            // 列选择把全部测点都关掉时回退为显示全部筛选测点,避免空表困惑。
            if(points.Count==0)points=allPoints.Select((p,index)=>new{Point=p,Index=index}).Where(x=>filter.Points.Contains(x.Point.name)).OrderBy(x=>DeviceRank(x.Point.binding.device)).ThenBy(x=>x.Index).Select(x=>x.Point).ToList();
            foreach(Point p in points){PointInfo info=PointCatalog.Get(p.name);string unit=(info.Unit??"").Replace(" · 倍率待核准","").Replace("· 倍率待核准","").Trim();grid.Columns.Add(p.name,(p.binding.device+"·"+info.Label+(String.IsNullOrEmpty(unit)?"":"（"+unit+"）")));}foreach(DataGridViewColumn c in grid.Columns)c.Width=112;
            foreach(var group in rows.GroupBy(r=>r.Session+"|"+r.Round).OrderByDescending(g=>g.Min(r=>r.RoundStartedUtc??r.Utc))){var byPoint=group.GroupBy(x=>x.Point).ToDictionary(g=>g.Key,g=>g.OrderBy(x=>x.Utc).First());StoredObservation sample=group.First();DateTime start=sample.RoundStartedUtc??group.Min(x=>x.Utc);var cells=new List<object>{start.ToLocalTime().ToString("yyyy-MM-dd HH:mm:ss.fff"),sample.Round};foreach(Point p in points){StoredObservation o;if(!byPoint.TryGetValue(p.name,out o)){cells.Add("");continue;}cells.Add(o.Number.HasValue?((object)o.Number.Value.ToString("G17",System.Globalization.CultureInfo.InvariantCulture)):((o.Quality=="good"?"":QualityLabel(o.Quality)+"：")+o.Value));}grid.Rows.Add(cells.ToArray());}}
        static int DeviceRank(string device){string[] order={"DS666","PLC","DDSU666","DJSF6682"};int i=Array.IndexOf(order,device);return i<0?Int32.MaxValue:i;}
        static string QualityLabel(string q){return q=="good"?"正常":q=="timeout"?"超时":q=="error"?"异常":q=="protocol_exception"?"协议异常":q=="decode_error"?"解码异常":String.IsNullOrEmpty(q)?"未知":q;}
        async Task ExportAsync(string format){if(exportCancel!=null)return;try{HistoryFilter f=MakeFilter();string sig=Signature(f);if(filterDirty||sig!=previewSignature){if(MessageBox.Show(this,"筛选条件尚未应用，是否先按当前条件查询并确认预览后导出？","确认导出范围",MessageBoxButtons.YesNo,MessageBoxIcon.Question)!=DialogResult.Yes)return;if(!await ApplyAndQuery())return;f=MakeFilter();sig=Signature(f);}if(sig!=previewSignature){throw new InvalidOperationException("当前预览与筛选条件不一致，请重新查询后导出。");}
          string destination=null;while(true){using(var d=new FolderBrowserDialog{Description="选择当前用户可写的导出目录。程序会先在临时目录生成，再复制到目标目录并原子发布。",ShowNewFolderButton=true}){if(!String.IsNullOrEmpty(destination))d.SelectedPath=destination;if(d.ShowDialog(this)!=DialogResult.OK)return;destination=d.SelectedPath;}try{ExportNaming.VerifyDestination(destination);ExportNaming.CheckDestinationSpace(destination);break;}catch(Exception ex){DialogResult retry=MessageBox.Show(this,ex.Message+"\r\n\r\n重新选择导出目录？筛选条件保持不变。","目标目录不可写",MessageBoxButtons.RetryCancel,MessageBoxIcon.Warning);if(retry!=DialogResult.Retry)return;}}
          exportCancel=new CancellationTokenSource();SetExporting(true);var progressReport=new Progress<ExportProgress>(p=>{if(!disposed){exportStatus.Visible=true;exportStatus.Text=p.Phase+" · "+p.CompletedRows.ToString("N0")+(p.TotalRows>0?" / "+p.TotalRows.ToString("N0"):"");}});ExportResult r=await ExperimentExport.ExportAsync(dataRoot,f,destination,format,progressReport,exportCancel.Token);if(!disposed){exportStatus.Visible=true;exportStatus.Text=(format=="xlsx"?"Excel":"CSV")+" · "+r.Rows.ToString("N0")+" 条完成";MessageBox.Show(this,"导出完成：\r\n"+r.OutputDirectory+"\r\n记录 "+r.Rows.ToString("N0")+" 条。","导出完成",MessageBoxButtons.OK,MessageBoxIcon.Information);}}
          catch(OperationCanceledException){if(!disposed){exportStatus.Visible=true;exportStatus.Text="导出已取消";}}catch(Exception ex){if(!disposed)MessageBox.Show(this,"导出未完成，数据库和既有文件未覆盖。\r\n"+ex.Message,"导出失败",MessageBoxButtons.OK,MessageBoxIcon.Warning);}finally{if(exportCancel!=null){exportCancel.Dispose();exportCancel=null;}if(!disposed)SetExporting(false);}}
        void SetExporting(bool busy){export.Enabled=!busy;query.Enabled=!busy;follow.Enabled=!busy;next.Enabled=!busy&&next.Enabled;cancel.Visible=busy;cancel.Enabled=busy;progress.Visible=busy;progress.Style=ProgressBarStyle.Marquee;}
        async void FollowTick(){if(disposed||!Visible)return;if(following)SetToNow();RefreshStorageStatus();if(DateTime.Now-lastInventory>TimeSpan.FromSeconds(15))RefreshInventory(false);if(!following)return;ExperimentStore st=engine.Store;long committed=st!=null&&st.Status!=null&&st.Status.Recording&&engine.ActiveSource==(string)source.SelectedItem?st.Committed:-1;if(filterDirty&&!queryBusy){lastCommitted=committed;await RunQuery(true);return;}long completed=engine.CompletedCaptures;if(committed!=lastCommitted||completed!=lastCompletedCaptures){lastCompletedCaptures=completed;lastCommitted=committed;await RunQuery(true);}}
        void LoadPartitionSetting(){string path=Path.Combine(appRoot,"partition-days.json");try{var s=new System.Web.Script.Serialization.JavaScriptSerializer().Deserialize<PartitionSetting>(File.ReadAllText(path));if(s.SerialDays>=1&&s.SerialDays<=3650)serialPartitionDays=s.SerialDays;if(s.SimulationDays>=1&&s.SimulationDays<=3650)simulationPartitionDays=s.SimulationDays;if(s.Days>=1&&s.Days<=3650){if(serialPartitionDays==30)serialPartitionDays=s.Days;if(simulationPartitionDays==30)simulationPartitionDays=s.Days;}}catch{}LoadSourcePartitionSetting();partitionPreset.SelectedIndexChanged+=(s,e)=>partitionCustom.Enabled=partitionPreset.SelectedIndex==3;}
        void LoadSourcePartitionSetting(){partitionDays=(string)source.SelectedItem=="serial"?serialPartitionDays:simulationPartitionDays;partitionCustom.Value=partitionDays;partitionPreset.SelectedIndex=partitionDays==7?0:partitionDays==15?1:partitionDays==30?2:3;partitionCustom.Enabled=partitionPreset.SelectedIndex==3;}
        int SelectedDays(){return partitionPreset.SelectedIndex==0?7:partitionPreset.SelectedIndex==1?15:partitionPreset.SelectedIndex==2?30:(int)partitionCustom.Value;}
        void ApplyPartition(bool immediate){try{partitionDays=SelectedDays();string selected=(string)source.SelectedItem;engine.ConfigurePartition(selected,partitionDays,immediate);if(selected=="serial")serialPartitionDays=partitionDays;else simulationPartitionDays=partitionDays;SavePartitionSetting();RefreshStorageStatus();}catch(Exception ex){MessageBox.Show(this,ex.Message,"分库设置",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
        void SavePartitionSetting(){string path=Path.Combine(appRoot,"partition-days.json"),tmp=path+".partial";Directory.CreateDirectory(appRoot);File.WriteAllText(tmp,new System.Web.Script.Serialization.JavaScriptSerializer().Serialize(new PartitionSetting{Days=partitionDays,SerialDays=serialPartitionDays,SimulationDays=simulationPartitionDays}));if(File.Exists(path))File.Replace(tmp,path,null);else File.Move(tmp,path);}
        void RefreshStorageStatus(){var st=engine.Store;string label="来源："+(source.SelectedItem as string=="serial"?"实机":"模拟")+"　·　分库："+partitionDays+" 天";if(st!=null&&st.Status!=null&&(string)source.SelectedItem==engine.ActiveSource){var s=st.Status;label+="　·　"+(s.Recording?"正在记录":"已停止")+"　·　已写入 "+s.Committed.ToString("N0")+" 条　·　队列 "+s.Pending+" 条 / "+(s.QueuedBytes/1024).ToString("N0")+" KiB　·　可用空间 "+(s.AvailableDiskBytes/1024/1024).ToString("N0")+" MiB";if(s.DiskWarning)label+="（磁盘空间偏低）";if(!String.IsNullOrEmpty(s.LastError))label+="　·　记录错误："+s.LastError;}storageStatus.Text=label+"　·　路径："+dataRoot;}
        sealed class InventoryEntry{public string Source,Path;}
        void RefreshInventory(bool force){if(inventoryBusy||disposed||(!force&&DateTime.Now-lastInventory<TimeSpan.FromSeconds(15)))return;inventoryBusy=true;lastInventory=DateTime.Now;Task<List<InventoryEntry>> load=Task.Run<List<InventoryEntry>>(()=>ExperimentHistory.Databases(dataRoot,"serial").Select(x=>new InventoryEntry{Source="serial",Path=x}).Concat(ExperimentHistory.Databases(dataRoot,"simulation").Select(x=>new InventoryEntry{Source="simulation",Path=x})).OrderBy(x=>x.Source).ThenBy(x=>x.Path).ToList());load.ContinueWith((Task<List<InventoryEntry>> t)=>{if(disposed)return;try{if(IsHandleCreated)BeginInvoke((Action)(()=>{try{inventory.Rows.Clear();if(t.IsFaulted)throw t.Exception;foreach(InventoryEntry entry in t.Result){FileInfo i=new FileInfo(entry.Path);inventory.Rows.Add(entry.Source=="serial"?"实机":"模拟",i.Name,(i.Length/1048576.0).ToString("N2"),i.Name.Contains((entry.Source=="serial"?serialPartitionDays:simulationPartitionDays)+"d")?"当前周期":"历史分库");}inventory.Rows.Add("",dataRoot,"","");}catch(Exception ex){feedback.Text="数据库清单读取失败："+ex.Message;}finally{inventoryBusy=false;}}));}catch{inventoryBusy=false;}});}
        public sealed class PartitionSetting{public int Days{get;set;}public int SerialDays{get;set;}public int SimulationDays{get;set;}}
        void DisposePage(){if(disposed)return;disposed=true;generation++;timer.Stop();timer.Dispose();if(exportCancel!=null)try{exportCancel.Cancel();}catch{} }
    }
}
