using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading;
using System.Threading.Tasks;
using System.Web.Script.Serialization;

namespace ExperimentMonitor {
    public sealed class DiagnosticResult {
        public int Slave, Address, Count; public string Mode, Status, Value, PayloadHex, TxHex, RxHex; public long Milliseconds; public DateTime Utc;
        public bool Success { get { return Status == "good"; } }
    }
    public sealed class PolicyChange { public string Type, Source, Detail; public DateTime Utc; public long Round; }
    public sealed class MonitorEngine:IDisposable {
        readonly List<Point> points; readonly string root; readonly object sync=new object();
        Thread worker; CancellationTokenSource cancel; bool disposed, disconnecting, diagnosticBusy, connected, connectedSimulation; string connectedPort=""; int connectedBaud;
        CancellationTokenSource diagnosticCancel; readonly ManualResetEvent diagnosticComplete=new ManualResetEvent(true);
        IReadTransport connectedTransport; bool single; int periodSeconds=2; readonly Dictionary<string,PartitionCycle> partitions=new Dictionary<string,PartitionCycle>();
        readonly string captureSession=Guid.NewGuid().ToString("N");
        internal Func<bool,string,int,IReadTransport> TransportFactory=(sim,port,baud)=>sim?(IReadTransport)new SimulationTransport():new SerialTransport(port,baud);
        public event Action<Observation> ObservationReceived; public event Action<string> StatusChanged; public event Action<string> LogReceived;
        public event Action<bool,string> ConnectionChanged; public event Action<PolicyChange> PolicyChanged;
        public ExperimentStore Store {get;private set;}
        long completedCaptures;
        public long CompletedCaptures { get { lock(sync)return completedCaptures; } }
        string lastStoreError = string.Empty;
        public string LastStoreError { get { lock(sync) return lastStoreError; } }
        public int PartitionDays {get {lock(sync){var p=GetPartition(connected?ActiveSource:"serial");return p.ActiveDays;}} set { ConfigurePartition(value,false); } }
        public int ActivePartitionDays {get {lock(sync)return GetPartition(connected?ActiveSource:"serial").ActiveDays;}}
        public int PendingPartitionDays {get {lock(sync)return GetPartition(connected?ActiveSource:"serial").PendingDays;}}
        public string PartitionSummary {get {lock(sync)return GetPartition(connected?ActiveSource:"serial").Summary(DateTime.UtcNow);}}
        public bool IsRunning {get {lock(sync)return worker!=null;}}
        public bool IsConnected {get {lock(sync)return connected;}}
        public string ActiveSource {get {lock(sync)return connected?(connectedSimulation?"simulation":"serial"):null;}}
        public bool ConnectedSimulation {get {lock(sync)return connected&&connectedSimulation;}}
        public string ConnectedPort {get {lock(sync)return connectedPort;}}
        public int ConnectedBaud {get {lock(sync)return connectedBaud;}}
        public int CurrentPeriodSeconds {get {lock(sync)return periodSeconds;}}
        volatile bool recordRawLog=true; public bool RecordRawLog {get{return recordRawLog;}set{recordRawLog=value;}}
        public MonitorEngine(List<Point> points,string root) {if(points==null)throw new ArgumentNullException("points");this.points=points;this.root=Path.GetFullPath(root);Directory.CreateDirectory(this.root);}
        void State(string s){var h=StatusChanged;if(h!=null)foreach(Action<string> f in h.GetInvocationList())try{f(s);}catch{}}
        void Log(string s){var h=LogReceived;if(h!=null)foreach(Action<string> f in h.GetInvocationList())try{f(s);}catch{}}
        void ConnectionState(bool state,string source){var h=ConnectionChanged;if(h!=null)foreach(Action<bool,string> f in h.GetInvocationList())try{f(state,source);}catch{}}
        void PublishObservation(Observation observation){var h=ObservationReceived;if(h!=null)foreach(Action<Observation> f in h.GetInvocationList())try{f(observation);}catch(Exception e){Log("界面观测通知失败："+e.Message);}}
        PartitionCycle GetPartition(string source){PartitionCycle p;if(!partitions.TryGetValue(source,out p)){string dir=Path.Combine(root,"data","storage");string settings=Path.Combine(root,"settings","partition-cycle-"+source+".json");p=new PartitionCycle(dir,source,settings);partitions.Add(source,p);}return p;}
        public void Connect(bool simulation,string port,int baud) {
            IReadTransport opened=null; lock(sync){if(disposed)throw new ObjectDisposedException("MonitorEngine");if(disconnecting)throw new InvalidOperationException("正在断开连接");if(diagnosticBusy)throw new InvalidOperationException("诊断读取完成前不能更改连接");if(worker!=null)throw new InvalidOperationException("请先停止采集");if(connected){if(connectedSimulation==simulation&&(simulation||String.Equals(connectedPort,port,StringComparison.OrdinalIgnoreCase))&&connectedBaud==baud)return;throw new InvalidOperationException("请先断开当前连接");}}
            if(!simulation&&String.IsNullOrWhiteSpace(port))throw new ArgumentException("请选择串口","port");
            opened=TransportFactory(simulation,port??"模拟",baud);
            string source=simulation?"simulation":"serial";
            try{PartitionCycle partition;lock(sync){if(disposed||disconnecting||connected)throw new InvalidOperationException("连接状态已改变，请重试");partition=GetPartition(source);}partition.EnsureInitialized(DateTime.UtcNow);}catch{opened.Dispose();throw;}
            lock(sync){if(disposed||disconnecting||connected){opened.Dispose();throw new InvalidOperationException("连接状态已改变，请重试");}connectedTransport=opened;connected=true;connectedSimulation=simulation;connectedPort=port??"模拟";connectedBaud=baud;}
            State((simulation?"模拟":"实机")+"已连接 · "+(simulation?"模拟端口":port)+" · "+baud+" 8N1");Log("连接成功 source="+source+" port="+connectedPort+" baud="+baud);ConnectionState(true,source);
        }
        public void Disconnect(){string source;lock(sync){if(!connected&&!diagnosticBusy)return;if(disconnecting)throw new InvalidOperationException("正在断开连接");disconnecting=true;source=connectedSimulation?"simulation":"serial";if(diagnosticCancel!=null)diagnosticCancel.Cancel();}try{Stop();if(!diagnosticComplete.WaitOne(10000))throw new TimeoutException("等待只读诊断结束超时，连接仍保留");IReadTransport closing=null;lock(sync){closing=connectedTransport;connectedTransport=null;connected=false;connectedPort="";connectedBaud=0;}try{if(closing!=null)closing.Dispose();}finally{State("已断开连接");Log("连接已断开 source="+source);ConnectionState(false,source);}}catch{lock(sync)disconnecting=false;throw;}finally{lock(sync)disconnecting=false;}}
        public void SetPeriodSeconds(int seconds){if(seconds<1||seconds>86400)throw new ArgumentOutOfRangeException("seconds","采集间隔范围为1到86400秒");PolicyChange change=null;lock(sync){if(periodSeconds==seconds)return;int previous=periodSeconds;periodSeconds=seconds;change=new PolicyChange{Type="period",Source=connected?(connectedSimulation?"simulation":"serial"):"",Utc=DateTime.UtcNow,Round=0,Detail=previous+"->"+seconds+" seconds (applies after current round)"};}RecordPolicy(change);}
        public void ConfigurePartition(int days,bool applyImmediately){string source;lock(sync)source=connected?(connectedSimulation?"simulation":"serial"):"serial";ConfigurePartition(source,days,applyImmediately);}
        public void ConfigurePartition(string source,int days,bool applyImmediately){if(source!="serial"&&source!="simulation")throw new ArgumentException("来源无效","source");if(days<1||days>3650)throw new ArgumentOutOfRangeException("days","分期范围为1到3650天");PartitionCycle p;long round;bool collecting;lock(sync){p=GetPartition(source);collecting=worker!=null&&connected&&(connectedSimulation?"simulation":"serial")==source;round=collecting?activeRound:0;}p.Configure(days,applyImmediately,DateTime.UtcNow,collecting,round);var c=new PolicyChange{Type="partition",Source=source,Utc=DateTime.UtcNow,Round=round,Detail="days="+days+"; immediate="+applyImmediately};RecordPolicy(c);}
        long activeRound;
        void RecordPolicy(PolicyChange c){var h=PolicyChanged;if(h!=null)foreach(Action<PolicyChange> f in h.GetInvocationList())try{f(c);}catch(Exception e){Log("策略通知失败："+e.Message);}Log("POLICY "+c.Type+" "+c.Detail);try{string dir=Path.Combine(root,"logs");Directory.CreateDirectory(dir);File.AppendAllText(Path.Combine(dir,"policy-events.jsonl"),new JavaScriptSerializer().Serialize(c)+Environment.NewLine,new System.Text.UTF8Encoding(false));}catch(Exception e){Log("策略变更日志写入失败："+e.Message);}ExperimentStore current;lock(sync)current=Store;if(current!=null)try{current.RecordPolicy(c.Type,c.Detail,c.Round,c.Utc);}catch(Exception e){Log("策略变更未写入数据库："+e.Message);}}
        public void Start(int period,int timeout,IEnumerable<string> selected){StartCore(period,timeout,selected,false);}
        public void StartOnce(int period,int timeout,IEnumerable<string> selected){StartCore(period,timeout,selected,true);}
        // Compatibility overloads are explicit about source identity and still require a prior Connect.
        public void Start(bool simulation,string port,int baud,int period,int timeout,IEnumerable<string> selected){EnsureSameConnection(simulation,port,baud);StartCore(period,timeout,selected,false);}
        public void StartOnce(bool simulation,string port,int baud,int period,int timeout,IEnumerable<string> selected){EnsureSameConnection(simulation,port,baud);StartCore(period,timeout,selected,true);}
        void EnsureSameConnection(bool sim,string port,int baud){lock(sync){if(!connected||connectedSimulation!=sim||connectedBaud!=baud||(!sim&&!String.Equals(connectedPort,port,StringComparison.OrdinalIgnoreCase)))throw new InvalidOperationException("请先连接所选数据源和串口");}}
        void StartCore(int period,int timeout,IEnumerable<string> selected,bool once){
            lock(sync){if(disposed)throw new ObjectDisposedException("MonitorEngine");if(disconnecting)throw new InvalidOperationException("正在断开连接");if(diagnosticBusy)throw new InvalidOperationException("诊断读取进行中，请完成后再采集");if(!connected||connectedTransport==null)throw new InvalidOperationException("请先连接数据源");if(worker!=null)throw new InvalidOperationException("采集已经运行");if(period<1||period>86400||timeout<1||timeout>30)throw new ArgumentOutOfRangeException("周期/超时");var ids=new HashSet<string>(selected??Enumerable.Empty<string>());var chosen=points.Where(p=>ids.Contains(p.name)).ToList();if(chosen.Count==0)throw new InvalidOperationException("请选择采集点");periodSeconds=period;lastStoreError=string.Empty;cancel=new CancellationTokenSource();var token=cancel.Token;single=once;bool sim=connectedSimulation;string port=connectedPort;int baud=connectedBaud;var transport=connectedTransport;var partition=GetPartition(sim?"simulation":"serial");worker=new Thread(()=>Run(sim,port,baud,timeout,chosen,token,transport,partition));worker.IsBackground=true;worker.Name="实验串口采集";try{worker.Start();}catch{worker=null;cancel.Dispose();cancel=null;throw;}}
        }
        void Run(bool sim,string port,int baud,int timeout,List<Point> chosen,CancellationToken token,IReadTransport transport,PartitionCycle partition){string source=sim?"simulation":"serial",session=Guid.NewGuid().ToString("N"),config="",version="";var failed=new Dictionary<int,int>();var probeAt=new Dictionary<int,DateTime>();ExperimentStore store=null;StreamWriter events=null;long round=0;try{
            config=File.ReadAllText(Path.Combine(root,"protocol.json"));using(var hash=SHA256.Create())version=PointCatalog.Version+"-"+BitConverter.ToString(hash.ComputeHash(System.Text.Encoding.UTF8.GetBytes(config))).Replace("-","");Directory.CreateDirectory(Path.Combine(root,"logs"));partition.EnsureInitialized(DateTime.UtcNow);events=OpenSessionLog(Path.Combine(root,"logs"),session);store=new ExperimentStore(Path.Combine(root,"data","storage"),source,new JavaScriptSerializer().Serialize(new{protocolJson=config,catalog=chosen.Select(p=>PointCatalog.Get(p)).ToArray(),configVersion=version}),partition.ActiveDays,partition.ResolvePath,session);store.Ready.GetAwaiter().GetResult();lock(sync)Store=store;
            Action<string> log=s=>{try{bool raw=s.StartsWith("TX ",StringComparison.Ordinal)||s.StartsWith("RX ",StringComparison.Ordinal)||s.StartsWith("[模拟] TX ",StringComparison.Ordinal)||s.StartsWith("[模拟] RX ",StringComparison.Ordinal)||s.StartsWith("发送前丢弃 RX ",StringComparison.Ordinal);if(!raw||RecordRawLog){events.WriteLine(DateTime.UtcNow.ToString("o")+" "+s);events.Flush();}}catch{}Log(s);};State((sim?"模拟":"实机")+"已连接 · 正在采集 · "+port+" · "+baud+" 8N1");var clock=Stopwatch.StartNew();long next=0;int timeoutMs=timeout*1000;
            while(true){token.ThrowIfCancellationRequested();round++;lock(sync)activeRound=round;DateTime roundStarted=DateTime.UtcNow;string roundPath=partition.BeginRound(roundStarted,round);try{
                foreach(var group in chosen.GroupBy(p=>p.binding.slave)){DateTime probe;if(probeAt.TryGetValue(group.Key,out probe)&&DateTime.UtcNow<probe)continue;foreach(var p in group){token.ThrowIfCancellationRequested();var meta=PointCatalog.Get(p);var o=Collector.Read(transport,p,meta.Mode,source,timeoutMs,token,log);o.SessionId=session;o.ConfigVersion=version;o.Round=round;o.RoundStartedUtc=roundStarted;o.Unit=meta.Unit;o.Description=meta.Label;if(o.Number.HasValue)o.Number*=meta.Scale;store.Record(o,round,meta.Unit,roundPath);PublishObservation(o);log("SAMPLE round="+round+" point="+o.Point+" quality="+o.Quality+" value="+o.Value);if(o.Quality=="timeout"||o.Quality=="error"){int n;failed.TryGetValue(group.Key,out n);failed[group.Key]=++n;int delay=Math.Min(60,5*(1<<Math.Min(n-1,3)));probeAt[group.Key]=DateTime.UtcNow.AddSeconds(delay);log("站号 "+group.Key+" 无有效响应，本轮跳过其余点，"+delay+"秒后探测；其他设备继续");lock(sync){if(Object.ReferenceEquals(connectedTransport,transport))connectedTransport=null;}try{transport.Dispose();}catch{}if(!sim&&token.WaitHandle.WaitOne(250))token.ThrowIfCancellationRequested();transport=TransportFactory(sim,port,baud);bool adopted=false;lock(sync){if(connected&&!disposed&&!disconnecting){connectedTransport=transport;adopted=true;}}if(!adopted){try{transport.Dispose();}catch{}token.ThrowIfCancellationRequested();throw new IOException("连接状态已改变，已释放新建通道");}break;}if(o.Quality=="good"&&failed.ContainsKey(group.Key)){failed.Remove(group.Key);probeAt.Remove(group.Key);log("站号 "+group.Key+" 已恢复");}}}
            }finally{partition.CompleteRound(round,DateTime.UtcNow);}if(!String.IsNullOrEmpty(store.LastError))throw new IOException("本地记录失败："+store.LastError);if(single)break;int period;lock(sync)period=periodSeconds;next+=period*1000L;while(next<=clock.ElapsedMilliseconds)next+=period*1000L;if(token.WaitHandle.WaitOne((int)Math.Min(Int32.MaxValue,Math.Max(0,next-clock.ElapsedMilliseconds))))token.ThrowIfCancellationRequested();}
            State(single?"单轮采集完成 · 连接保持 · 本地记录已保存":"采集已停止 · 连接保持 · 本地记录已保存");
        }catch(OperationCanceledException){State("采集已停止 · 连接保持 · 旧值保留，本地记录已保存");}catch(Exception ex){State("采集停止："+ex.Message);Log(ex.ToString());}finally{if(store!=null){try{store.FlushAsync().GetAwaiter().GetResult();}catch(Exception e){Log("等待本地记录完成失败："+e.Message);lock(sync)if(String.IsNullOrEmpty(lastStoreError))lastStoreError=e.Message;}if(!String.IsNullOrEmpty(store.LastError)){lock(sync)lastStoreError=store.LastError;}try{store.Dispose();}catch(Exception e){Log("本地记录关闭失败："+e.Message);lock(sync)if(String.IsNullOrEmpty(lastStoreError))lastStoreError=e.Message;}}if(events!=null)try{events.Dispose();}catch(Exception e){Log("采集日志关闭失败："+e.Message);}bool notifyDisconnect=false;lock(sync){if(connected&&connectedTransport==null){connected=false;connectedPort="";connectedBaud=0;notifyDisconnect=true;}completedCaptures++;Store=null;if(worker==Thread.CurrentThread)worker=null;if(cancel!=null){cancel.Dispose();cancel=null;}activeRound=round;}if(notifyDisconnect){State("串口重连失败，连接已断开，请手动重新连接");ConnectionState(false,source);}}
        }
        public void Stop(){Thread t;lock(sync){if(cancel!=null)cancel.Cancel();t=worker;}if(t!=null&&!t.Join(10000))throw new TimeoutException("正在等待采集记录写入完成，请稍后重试");}
        sealed class DiagnosticContext { public IReadTransport Transport; public string Source; public CancellationToken Token; }
        DiagnosticContext BeginDiagnostic(){lock(sync){if(disposed)throw new ObjectDisposedException("MonitorEngine");if(disconnecting)throw new InvalidOperationException("正在断开连接");if(!connected||connectedTransport==null)throw new InvalidOperationException("请先连接数据源");if(worker!=null)throw new InvalidOperationException("请先停止采集再进行诊断读取");if(diagnosticBusy)throw new InvalidOperationException("已有诊断读取正在进行");diagnosticBusy=true;diagnosticCancel=new CancellationTokenSource();diagnosticComplete.Reset();return new DiagnosticContext{Transport=connectedTransport,Source=connectedSimulation?"simulation":"serial",Token=diagnosticCancel.Token};}}
        void EndDiagnostic(){lock(sync){diagnosticBusy=false;if(diagnosticCancel!=null){diagnosticCancel.Dispose();diagnosticCancel=null;}diagnosticComplete.Set();}}
        public Task<DiagnosticResult> ReadDiagnosticAsync(int slave,int address,int count,string mode,int timeoutSeconds){if(timeoutSeconds<1||timeoutSeconds>30)throw new ArgumentOutOfRangeException("timeoutSeconds");Modbus.Request(slave,address,count);var context=BeginDiagnostic();return Task.Run(()=>{try{return ReadDiagnosticCore(context,slave,address,count,mode,timeoutSeconds);}finally{EndDiagnostic();}});}
        public DiagnosticResult ReadDiagnostic(int slave,int address,int count,string mode,int timeoutSeconds){if(timeoutSeconds<1||timeoutSeconds>30)throw new ArgumentOutOfRangeException("timeoutSeconds");Modbus.Request(slave,address,count);var context=BeginDiagnostic();try{return ReadDiagnosticCore(context,slave,address,count,mode,timeoutSeconds);}finally{EndDiagnostic();}}
        DiagnosticResult ReadDiagnosticCore(DiagnosticContext context,int slave,int address,int count,string mode,int timeoutSeconds){var r=new DiagnosticResult{Slave=slave,Address=address,Count=count,Mode=mode??"RAW",Utc=DateTime.UtcNow};var sw=Stopwatch.StartNew();byte[] tx=Modbus.Request(slave,address,count);r.TxHex=Modbus.Hex(tx);try{byte[] rx=context.Transport.Read(slave,address,count,timeoutSeconds*1000,context.Token,Log);r.RxHex=Modbus.Hex(rx);var b=new List<byte>(rx);byte[] frame;if(!Modbus.Extract(b,slave,count,out frame)||b.Count!=0||frame.Length!=rx.Length)throw new InvalidDataException("响应CRC、站号或长度不匹配");if(frame[1]==0x83){r.Status="protocol_exception";r.Value="设备异常码 0x"+frame[2].ToString("X2");}else{byte[] payload=frame.Skip(3).Take(count*2).ToArray();double? v;string value=Modbus.Decode(payload,r.Mode,out v);r.Status=value.StartsWith("非有限")?"decode_error":"good";r.Value=value;r.PayloadHex=Modbus.Hex(payload);}}catch(OperationCanceledException e){r.Status="cancelled";r.Value=String.IsNullOrEmpty(e.Message)?"诊断读取已取消":e.Message;}catch(TimeoutException e){r.Status="timeout";r.Value=e.Message;}catch(Exception e){r.Status="error";r.Value=e.Message;}r.Milliseconds=sw.ElapsedMilliseconds;r.Utc=DateTime.UtcNow;string diag="DIAGNOSTIC source="+context.Source+" slave="+slave+" address="+address+" count="+count+" mode="+r.Mode+" status="+r.Status+(RecordRawLog?" TX="+r.TxHex+" RX="+r.RxHex+" payload="+r.PayloadHex:"");Log(diag);if(RecordRawLog)try{Directory.CreateDirectory(Path.Combine(root,"logs"));File.AppendAllText(Path.Combine(root,"logs","diagnostics.jsonl"),new JavaScriptSerializer().Serialize(r)+Environment.NewLine,new System.Text.UTF8Encoding(false));}catch(Exception e){Log("诊断日志写入失败："+e.Message);}return r;}
        static StreamWriter OpenSessionLog(string directory,string session){string name="session-"+DateTime.Now.ToString("yyyyMMdd-HHmmssfff")+"-"+session+".log";return new StreamWriter(new FileStream(Path.Combine(directory,name),FileMode.CreateNew,FileAccess.Write,FileShare.Read),new System.Text.UTF8Encoding(true));}
        public void Dispose(){lock(sync)if(disposed)return;Disconnect();lock(sync)disposed=true;foreach(var p in partitions.Values)p.Dispose();diagnosticComplete.Dispose();}
    }
}
